### PR TITLE
new plugs

### PR DESCRIPTION
**Pull request by Ward6548**

### CODE REVIEW

**Review by Antondj5 — CHANGES_REQUESTED** [review]
You forgot to add:
* dice
* executeQuery
* findSalesforceCase

**Comment by Ward6548** [comment]
Nice did you that so quickly? 👍 
findSalesforceCase is called findCaseFromSalesforce though. Added the others

**Review by Antondj5 — CHANGES_REQUESTED** [review]
findCaseFromSalesforce is still missing

**Comment by Ward6548** [comment]
Oof.. I need a coffee

**Review by Antondj5 — APPROVED** [review]

**Pull request merged**
