### PR TITLE
Add query data sensor

### PR DESCRIPTION
**Pull request by SanderVanhove**
See implementation here: https://staging.waylay.io/#/edit/sensor/timeseriesQueryData/1.1.0

### CODE REVIEW

**Comment by Sam-Persoon** [comment]
I would add in the description that you should specify 2 of those 3 options. All 3 isn't allowed. 

I would also just return the data and not the entire payload returned by TSA (unless I am mistaken and this is happening behind the scenes). 
I think it also would be nice to the option to strip the timestamp column, as most of the time you are not interesting in them.

**Comment by SanderVanhove** [comment]
> I would add in the description that you should specify 2 of those 3 options. All 3 isn't allowed.

They are always optional, will add.

> I would also just return the data and not the entire payload returned by TSA (unless I am mistaken and this is happening behind the scenes).

Yeah was thinking about that. Then I should do more error handling for when something goes wrong on the backend.

> I think it also would be nice to the option to strip the timestamp column, as most of the time you are not interesting in them.

I don't know if this is that common. I think it should be handle in a script sensor if that is what you want, they are still timeseries.

**Comment by Sam-Persoon** [comment]
> > I think it also would be nice to the option to strip the timestamp column, as most of the time you are not interesting in them.
> 
> I don't know if this is that common. I think it should be handle in a script sensor if that is what you want, they are still timeseries.

I think it would definitely be helpful for chaining it into the BYOML sensor, then nothing else need to happen anymore for most sklearn models and the script sensor can be skipped. But I agree it is a bit questionable. We could also make a variant of this one that does that to prevent having too much properties.

**Comment by Sam-Persoon** [comment]
Just a typo in properties listing:
`columnnwise` --> `columnwise`

**Review by Sam-Persoon — APPROVED** [review]

**Pull request merged**
